[package]
name = "day-10"
version = "0.1.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"

[dependencies]
scan_fmt = "0.1.3"
chrono = "0.4.6"
cute = "0.3.0"
itertools = "0.8.0"
ndarray = "0.12.1"
rayon = "1.0.3"
